save_current_target_temperatrure:
  description: Save the current target temperature for later restore.
  fields:
    entity_id:
      description: Name of the better thermostat entity.
      example: "climate.better_thermostat_room"
  target:
    entity:
      integration: better_thermostat
      domain: climate

restore_saved_target_temperatrure:
  description: Restore the saved target temperature.
  fields:
    entity_id:
      description: Name of the better thermostat entity.
      example: "climate.better_thermostat_room"
  target:
    entity:
      integration: better_thermostat
      domain: climate

set_temp_target_temperatrure:
  description: Set the target temperature to a temporay like night mode, and save the old one.
  fields:
    entity_id:
      description: Name of the better thermostat entity.
      example: "climate.better_thermostat_room"
    temperature:
      name: Target temperature
      description: The target temperature to set.
      example: 18.5
      required: true
      advanced: true
      selector:
        number:
          min: 0
          max: 35
          step: 0.5
          mode: box
  target:
    entity:
      integration: better_thermostat
      domain: climate