default_config:

logger:
  default: error
  logs:
    custom_components.better_thermostat: debug

climate:
  - platform: generic_thermostat
    name: Study
    heater: input_boolean.heater
    target_sensor: input_number.indoor_temperature

input_number:
  external_sensor:
    name: External Sensor
    initial: 18
    min: 5
    max: 35
    step: 1

template:
  - sensor:
      - name: "External Temperature Sensor"
        unique_id: external_temperature_sensor
        state_class: measurement
        device_class: temperature
        unit_of_measurement: "°C"
        state: '{{ states.input_number.external_sensor.state | round(1, default=18) }}'


# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:


